### ISSUE TITLE
Improve API architecture

### ISSUE THREAD

**Issue by aochagavia** [aochagavia/sudoku#3]
Maybe it would be interesting to provide a `Solver` trait and different solver algorithms implementing it. This way, you could do something like `Sudoku::solve_with(BruteForce)` or something like that.

@Emerentius any thoughts on this?

**Comment by Emerentius** [comment]
For solvers that guarantee a solution, I don't see the point. There'd only be speed differences.

It could be useful to emulate a human person. Basically, I'm thinking of an interactive sudoku solver in the web or as a standalone (What else do you do with a sudoku library?).
A solver that uses certain logical patterns like naked singles, hidden singles, x-wing, swordfish what have you. You could implement a hinter, that eliminates possibitilies based on some subset of algorithms that eliminates possibilites and/or finds deducible entries.
Such a logic solver could use freely combinable algorithms. There's the question of ordering and repetition. These algorithms synergize.

Now you could implement such a thing to work with the bare sudoku, but depending on what extra information you're saving for solving, there are easier, faster ways. Naked singles and hidden singles for examples are very easy to find in the current solver as a consequence of the exact cover approach.

**Comment by aochagavia** [comment]
I guess this issue is related to the scope of the library, which could be one of the following:
1. Solve sudokus as fast as possible.
2. Showcase different approaches to sudoku solving, for learning purposes.
3. Provide step by step solving and hints (for instance, by emulating a human player).

I wrote this library as a personal challenge to design a solving algorithm without previous knowledge of other algorithms. That means I wrote the solver from my own experience solving sudokus manually, which is a naive approach as you can deduce from its horrible performance. With your pull request, the library seems to be aiming at "solve sudokus fast". I think this is a good direction to take, so the current architecture should be OK.
