### ISSUE TITLE
Read standard sudoku format

### ISSUE THREAD

**Issue by Emerentius** [aochagavia/sudoku#6]
The common format for a given sudoku is a single line of 81 digits or dots like so:
`59.....486.8...3.7...2.1.......4.....753.698.....9.......8.3...2.6...7.934.....65 comment with spaces`

We should be able to read this. We can keep our current format, too, if we either make it more forgiving or try parsing one, then the other.

**Comment by aochagavia** [comment]
Is this some kind of standard? Or does it just happen to be common throughout different implementations? Either way, it seems right to support it as well.

I feel more inclined towards removing the current format. We could implement a forgiving parser that ignores all characters that are not numeric and not a dot. This would allow to write things like:

```
let sudoku_str = "\
...|2..|.63
3..|..5|4.1
..1|..3|98.
...|...|.9.
...|538|...
.3.|...|...
.26|3..|5..
5.3|7..|..8
47.|..1|...";
```

This looks a lot like what we have now. It would also parse things like:

```
let sudoku_str = "\
...|2..|.63
3..|..5|4.1
..1|..3|98.
-----------
...|...|.9.
...|538|...
.3.|...|...
-----------
.26|3..|5..
5.3|7..|..8
47.|..1|...";
```

**Comment by Emerentius** [comment]
All the ones I've seen are. My sample consists of mostly the 4 datasets linked in [this github repo](https://github.com/attractivechaos/plb/tree/master/sudoku/incoming). All 4 links point to different websites (2 are dead and are preserved under releases in that repo), so it's not by one person. 
[This page here](http://sudopedia.enjoysudoku.com/Invalid_Test_Cases.html) also gives a string in that format for each example. I converted the hard sudokus file used in the benches and tests for this project from that format.

I'm fine with dropping the old format, though I'd prefer to keep it or get it back later (maybe support dots as placeholder), because it's more human-readable. But I don't feel very strongly on it.
A too forgiving parser could lead to strange problems with comments because there could be numbers in there. I'd enforce one format for the entire string. You'll know which by the 10th entry.

**Comment by aochagavia** [comment]
Sounds like a good idea. I don't mind keeping the old format either.
